/** File generated by Grunt -- do not modify
 *  JQUERY-FORM-VALIDATOR
 *
 *  @version 4.2.0
 *  @website https://github.com/premento/jQuery-Form-Validator
 *  @author Premento, https://github.com/premento
 *  @license MIT
 */
((e,r)=>{void 0===e&&void 0!==window&&(e=window),"function"==typeof define&&define.amd?define(["jquery"],r):"object"==typeof module&&module.exports?module.exports=r(require("jquery")):r(e.jQuery)})(this,function(e){(e=e).formUtils.registerLoadedModule("brazil"),e.formUtils.addValidator({name:"cpf",validatorFunction:function(e){var r,n=e.replace(/\D/g,""),o=0,a=0,e=0,t=0;if(11!==n.length||"00000000000"===n)return!1;for(r=1;r<=9;r++)o+=parseInt(n.substring(r-1,r))*(11-r);if((e=10<=(e=10*o%11)?0:e)!==parseInt(n.substring(9,10)))return!1;for(r=1;r<=10;r++)a+=parseInt(n.substring(r-1,r))*(12-r);return(t=10<=(t=10*a%11)?0:t)===parseInt(n.substring(10,11))},errorMessage:"",errorMessageKey:"badBrazilCPFAnswer"}),e.formUtils.addValidator({name:"brphone",validatorFunction:function(e){return!!e.match(/^(\+[\d]{1,3}[\s]{0,1}){0,1}(\(){0,1}(\d){2}(\)){0,1}(\s){0,1}(\d){4,5}([-. ]){0,1}(\d){4}$/g)},errorMessage:"",errorMessageKey:"badBrazilTelephoneAnswer"}),e.formUtils.addValidator({name:"cep",validatorFunction:function(e){return!!e.match(/^(\d){5}([-. ]){0,1}(\d){3}$/g)},errorMessage:"",errorMessageKey:"badBrazilCEPAnswer"})});