/** File generated by Grunt -- do not modify
 *  JQUERY-FORM-VALIDATOR
 *
 *  @version 2.3.79
 *  @website http://formvalidator.net/
 *  @author Victor Jonsson, http://victorjonsson.se
 *  @license MIT
 */
((e,r)=>{void 0===e&&void 0!==window&&(e=window),"function"==typeof define&&define.amd?define(["jquery"],r):"object"==typeof module&&module.exports?module.exports=r(require("jquery")):r(e.jQuery)})(this,function(e){(e=e).formUtils.registerLoadedModule("brazil"),e.formUtils.addValidator({name:"cpf",validatorFunction:function(e){var r=e.replace(/\D/g,""),n=0,o=0,e=0,a=0;if(11!==r.length||"00000000000"===r)return!1;for(i=1;i<=9;i++)n+=parseInt(r.substring(i-1,i))*(11-i);if((e=10<=(e=10*n%11)?0:e)!==parseInt(r.substring(9,10)))return!1;for(i=1;i<=10;i++)o+=parseInt(r.substring(i-1,i))*(12-i);return(a=10<=(a=10*o%11)?0:a)===parseInt(r.substring(10,11))},errorMessage:"",errorMessageKey:"badBrazilCPFAnswer"}),e.formUtils.addValidator({name:"brphone",validatorFunction:function(e){return!!e.match(/^(\+[\d]{1,3}[\s]{0,1}){0,1}(\(){0,1}(\d){2}(\)){0,1}(\s){0,1}(\d){4,5}([-. ]){0,1}(\d){4}$/g)},errorMessage:"",errorMessageKey:"badBrazilTelephoneAnswer"}),e.formUtils.addValidator({name:"cep",validatorFunction:function(e){return!!e.match(/^(\d){5}([-. ]){0,1}(\d){3}$/g)},errorMessage:"",errorMessageKey:"badBrazilCEPAnswer"})});