/** File generated by Grunt -- do not modify
 *  JQUERY-FORM-VALIDATOR
 *
 *  @version 2.3.79
 *  @website http://formvalidator.net/
 *  @author Victor Jonsson, http://victorjonsson.se
 *  @license MIT
 */
((e,t)=>{void 0===e&&void 0!==window&&(e=window),"function"==typeof define&&define.amd?define(["jquery"],t):"object"==typeof module&&module.exports?module.exports=t(require("jquery")):t(e.jQuery)})(this,function(e){var a;(a=e).formUtils.registerLoadedModule("jsconf"),a.setupValidation=function(e){var o=a(e.form||"form");a.each(e.validate||e.validation||{},function(e,t){var i="#"===e[0]?a(e):"."===e[0]?o.find(e):o.find('*[name="'+e+'"]');i.attr("data-validation",t.validation),a.each(t,function(e,t){"validation"!==e&&!1!==t&&(!0===t&&(t="true"),"_"===e[0]?(e=e.substring(1),!1===t?i.removeAttr(e):i.attr(e,t)):i.valAttr(e,t))})}),a.validate(e)}});