/** File generated by Grunt -- do not modify
 *  JQUERY-FORM-VALIDATOR
 *
 *  @version 2.3.79
 *  @website http://formvalidator.net/
 *  @author Victor Jonsson, http://victorjonsson.se
 *  @license MIT
 */
((e,r)=>{void 0===e&&void 0!==window&&(e=window),"function"==typeof define&&define.amd?define(["jquery"],r):"object"==typeof module&&module.exports?module.exports=r(require("jquery")):r(e.jQuery)})(this,function(e){(e=e).formUtils.registerLoadedModule("poland"),e.formUtils.addValidator({name:"plpesel",validatorFunction:function(e){var r=[1,3,7,9,1,3,7,9,1,3],t=0,o=0;if(/\d{11}/.test(e)&&11===e.length){for(var a=0;a<10;a++)t+=e[a]*r[a];if(t%10!=0&&(o=10-t%10),parseInt(e.charAt(10))===o)return!0}return!1},errorMessage:"",errorMessageKey:"badPlPesel"}),e.formUtils.addValidator({name:"plnip",validatorFunction:function(e){var r=[6,5,7,2,3,4,5,6,7],t=0;if(/\d{10}/.test(e)&&10===e.length){for(var o=0;o<9;o++)t+=e[o]*r[o];if(parseInt(e.charAt(9))===t%11)return!0}return!1},errorMessage:"",errorMessageKey:"badPlNip"}),e.formUtils.addValidator({name:"plregon",validatorFunction:function(e){var r=[8,9,2,3,4,5,6,7],t=[2,4,8,5,0,9,7,3,6,1,2,4,8],o=0,a=0;if(/(\d{14}|\d{9})/.test(e)&&(9===e.length||14===e.length)){for(var n=0;n<8;n++)o+=e[n]*r[n];if(o%11!=10&&(a=o%11),parseInt(e.charAt(8))===a){if(14!==e.length)return!0;for(n=o=0;n<13;n++)o+=e[n]*t[n];if(o%11!=10&&(a=o%11),parseInt(e.charAt(13))===a)return!0}}return!1},errorMessage:"",errorMessageKey:"badPlRegon"})});