/** File generated by Grunt -- do not modify
 *  JQUERY-FORM-VALIDATOR
 *
 *  @version 2.3.79
 *  @website http://formvalidator.net/
 *  @author Victor Jonsson, http://victorjonsson.se
 *  @license MIT
 */
((r,e)=>{void 0===r&&void 0!==window&&(r=window),"function"==typeof define&&define.amd?define(["jquery"],e):"object"==typeof module&&module.exports?module.exports=e(require("jquery")):e(r.jQuery)})(this,function(r){(r=r).formUtils.registerLoadedModule("uk"),r.formUtils.addValidator({name:"ukvatnumber",validatorFunction:function(r){if((r=r.replace(/[^0-9]/g,"")).length<9)return!1;var e=!1,t=r.split(""),r=Number(t[7]+t[8]),o=t[0],a=t[1];if(0===o&&0<a)return!1;for(var n=0,i=0;i<7;i++)n+=t[i]*(8-i);for(var d=0,s=8;2<=s;s--)t[d],d++;for(;0<n;)n-=97;return(e=r===(n=Math.abs(n))?!0:e)||(55<=(n%=97)?n-=55:n+=42,n===r&&(e=!0)),e},errorMessage:"",errorMessageKey:"badUKVatAnswer"}),r.formUtils.addValidator({name:"ukutr",validatorFunction:function(r){var e=[0,6,7,8,9,10,5,4,3,2],t=0;if(/\d{10}/.test(r)&&10===r.length){for(var o=0;o<10;o++)t+=r[o]*e[o];if(parseInt(r.charAt(0))===[2,1,9,8,7,6,5,4,3,2,1][t%11])return!0}return!1},errorMessage:"",errorMessageKey:"badUkUtr"}),r.formUtils.addValidator({name:"uknin",validatorFunction:function(r){return!!/^(?!BG)(?!GB)(?!NK)(?!KN)(?!TN)(?!NT)(?!ZZ)(?:[A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])(?:\s*\d\s*){6}([A-D]|\s)$/i.test(r)},errorMessage:"",errorMessageKey:"badUkNin"})});